#!/usr/bin/env node
/**
 * Embeds static assets (DaisyUI CSS, Tailwind JS) into a JavaScript module
 * Run this before building with Bun to ensure assets are bundled
 */

import { readFileSync, writeFileSync, mkdirSync } from 'fs';
import { dirname, join } from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const rootDir = join(__dirname, '..');

const publicDir = join(rootDir, 'src', 'public');
const assetsDir = join(rootDir, 'src', 'assets');

// Ensure assets directory exists
mkdirSync(assetsDir, { recursive: true });

console.log('Embedding static assets...');

// Read the CSS and JS files
const daisyuiCss = readFileSync(join(publicDir, 'daisyui.css'), 'utf-8');
const tailwindJs = readFileSync(join(publicDir, 'tailwind.js'), 'utf-8');

// Generate the embedded module
const embeddedModule = `// Auto-generated by scripts/embed-assets.js - DO NOT EDIT
// Re-run: node scripts/embed-assets.js

export const DAISYUI_CSS = ${JSON.stringify(daisyuiCss)};

export const TAILWIND_JS = ${JSON.stringify(tailwindJs)};
`;

const outputPath = join(assetsDir, 'embedded.js');
writeFileSync(outputPath, embeddedModule);

console.log(`Assets embedded to: ${outputPath}`);
console.log(`  - DaisyUI CSS: ${(daisyuiCss.length / 1024).toFixed(1)} KB`);
console.log(`  - Tailwind JS: ${(tailwindJs.length / 1024).toFixed(1)} KB`);
